config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"
    resources :restaurants, except: [:index] 
    
    get 'restaurantss/:id/form_turbo_stream', to: 'restaurants#form_turbo_stream', as: :form_turbo_stream
    
    resources :convertations do
      resources :messages
      
    end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/convertation.rb
class Convertation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where('(convertations.sender_id = ? AND convertations.recipient_id = ?) OR (convertations.sender_id = ? AND convertations.recipient_id = ?)',
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :convertation
  belongs_to :user
  validates_presence_of :body, :convertation_id, :user_id
  def message_time
    created_at.strftime('%m/%d/%Y at %l:%M %p')
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: {message: "No puede estar vacío este campo"}
  # after_create_commit do
  #   # broadcast_update_to :restaurants, target: "notificaciones", partial: "restaurants/notificaciones", locals: { count: Restaurant.where(user: current_user).count}
  #   # broadcast_update_to :restaurants, target: "nuevo_mensaje", partial: "restaurants/mensaje", locals: { mensaje: "manuel Ferrer" }
  #   # broadcast_prepend_to :restaurants
  # end
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/convertations_controller.rb
class ConvertationsController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
    @convertations = Convertation.all
  end

  def create
    if Convertation.between(params[:sender_id],params[:recipient_id])
      .present?
        @convertation = Convertation.between(params[:sender_id],
        params[:recipient_id]).first
    else
      @convertation = Convertation.create!(convertation_params)
    end
    redirect_to convertation_messages_path(@convertation)
  end

  private
  def convertation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @convertation = Convertation.find(params[:convertation_id])
  end

  def index
    @messages = @convertation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
      end
      if params[:m]
      @over_ten = false
      @messages = @convertation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
      @messages.last.read = true;
      end
    end
    @message = @convertation.messages.new
  end
  def new
    @message = @convertation.messages.new
  end

  def create
    @message = @convertation.messages.new(message_params)
    if @message.save
      Turbo::StreamsChannel.broadcast_append_to @convertation.id, target: "messages", partial: "messages/message", locals: { message: @message}
      redirect_to convertation_messages_path(@convertation)
    end

  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants
  def index

    @restaurants = Restaurant.all
    @count =@restaurants.count
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new


  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        @count = Restaurant.all.count

        Turbo::StreamsChannel.broadcast_update_to :restaurants, target: "notificaciones", partial: "restaurants/notificaciones", locals: { count: Restaurant.all.count}
        Turbo::StreamsChannel.broadcast_update_to :restaurants, target: "nuevo_mensaje", partial: "restaurants/mensaje", locals: { mensaje: "manuel Ferrer" }
        Turbo::StreamsChannel.broadcast_prepend_to :restaurants, target: "restaurants", partial: "restaurants/restaurant", locals: { restaurant: @restaurant }
        # format.html { redirect_to @restaurant, notice: "Restaurant was successfully created."}
        format.turbo_stream
        flash.now[:notice] = "Restaurant was successfully created."
      else
        format.html { render :new, status: :unprocessable_entity}
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: { restaurant: @restaurant } }
      end
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  # PATCH/PUT /restaurants/1
  def update
      if @restaurant.update(restaurant_params)
        notify_all_users
        # @mensaje = "Restaurant was successfully created."
        # flash[:notice] = @mensaje
          # redirect_to root_path, notice: "Restaurant was successfully created."
          # @restaurants = Restaurant.all
          flash.now[:notice] = "Restaurant was successfully created."
          render partial: "restaurants/restaurant", locals: { restaurant: @restaurant }
          # format.turbo_stream

      else
        render :edit, status: :unprocessable_entity
      end
  end

   
  def form_turbo_stream
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.turbo_stream
    end
  end 

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to root_path, notice: "Restaurant was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def notify_all_users
      ActionCable.server.broadcast("restaurant_#{@restaurant.id}",
        {action: 'updated'})
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convertations_helper.rb
module ConvertationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/convertations/index.html.erb
<div class="ui segment">
 <h3>Mailbox</h3>
 <div class="ui list">
  <div class="item">
    <% @convertations.each do |convertation| %>
      <% if convertation.sender_id == current_user.id ||      convertation.recipient_id == current_user.id %>
        <% if convertation.sender_id == current_user.id %>
          <% recipient = User.find(convertation.recipient_id) %>
        <% else %>
          <% recipient = User.find(convertation.sender_id) %>
        <% end %>
        <%= link_to recipient.email,   convertation_messages_path(convertation)%>
      <% end %>
    <% end %>
  </div>
 </div>
</div>
<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.email %> <%= link_to "Message me!", convertations_path(sender_id: current_user.id, recipient_id: user.id), method: :post%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurvboTests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller='test' data-color="rojo">
    <%= render "shared/navbar" %>
    <div class="container">
      <%= turbo_stream_from :restaurants %>
      <%= render "restaurants/notificaciones", count: @count %>
      <%#= render "restaurants/mensaje", mensaje: "" %>
      <%= current_user.email if current_user %>
      <%= yield %>
      <%= render "shared/flashes" %>
    </div>
  </body>
</html>
<style>
  .flash-messages {
  position: fixed;
  bottom: 20px;
  right: -0;
  background-color: #ffffff;
  padding: 10px;
  border: 1px solid #cccccc;
  border-radius: 5px;
  text-align: center;
}

.container {
  position: relative;
}

.badge {
  position: absolute;
  top: 10px;
  right: 660px;
  background-color: red;
  color: white;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.text {
  font-size: 12px;
}



</style>

app/views/messages/_message.html.erb
<% if message.body %>
  <div><% user = User.find(message.user_id) %></div>
  <div><%= user.email %><%= message.message_time %></div>
  <div><%= message.body %></div>
<% end %>

app/views/messages/index.html.erb
<%= turbo_stream_from @convertation.id %>
<div id="messages">
  <% @messages.each do |message| %>
    <%= render "message", message: message %>
  <% end %>
</div>

<%= form_for [@convertation, @message] do |f| %>
  <%= f.text_area :body %>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <%= f.submit "Send Reply" %>
<% end %>

app/views/restaurants/_form.html.erb
<%= turbo_frame_tag restaurant do %>
  <%= simple_form_for restaurant, html: { class: "shadow border my-2 p-3"} do |f| %>
  <h1>New restaurant</h1>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :rating %>
      <%= f.association :user, collection: User.all, label_method: :email, value_method: :id, include_blank: true %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>

app/views/restaurants/_form_turbo_stream.html.erb
<%= simple_form_for restaurant, url: restaurant_path(restaurant), method: :patch, html: { class: 'd-flex' }  do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_notificaciones.html.erb
<div class="container px-0 pt-4" id="notificaciones">
  <div class="badge">
    <span class="text"><%= count %></span>
  </div>
  <h2 class="border text-center w-50">Restaurants</h2>
</div>

app/views/restaurants/_restaurant.html.erb
<%= turbo_frame_tag restaurant do %>
  <%= render "shared/flashes" %>
  <h1><%= Time.now %></h1>
  <div id="<%= dom_id restaurant %>" class='border shadow p-3 my-2'>
    <p>
      <strong>Name:</strong>
      <%= restaurant.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= restaurant.address %>
    </p>

    <p>
      <strong>Rating:</strong>
      <%= restaurant.rating %>
    </p>

    <p>
      <%= link_to "Show this restaurant", restaurant_path(restaurant), data: {turbo_frame: restaurant} %>
    </p>
  </div>
<% end %>

app/views/restaurants/create.turbo_stream.erb
<%= turbo_stream.prepend "restaurants", partial: 'restaurants/restaurant', locals: {restaurant: @restaurant} %>
<%= turbo_stream.replace "notificaciones", partial: 'restaurants/notificaciones', locals: {count: @count} %>

<%= turbo_stream.replace "new_restaurant",
partial: "form", locals: { restaurant: Restaurant.new } %>
<%= turbo_stream.replace "my-alert", partial: "shared/flashes" %>

app/views/restaurants/edit.html.erb
<%= turbo_frame_tag @restaurant do %>
  <%= render "form", restaurant: @restaurant %>
<% end %>

app/views/restaurants/form_turbo_stream.html.erb
<%= render 'form_turbo_stream', restaurant: @rest %>

app/views/restaurants/form_turbo_stream.turbo_stream.erb
<!-- app/views/restaurants/form_turbo_stream.turbo_stream.erb -->
<%= turbo_stream.replace dom_id(@restaurant, :ts) do %>
<%= turbo_frame_tag dom_id(@restaurant, :ts )do  %>
  <%= render partial: "form_turbo_stream", locals: { restaurant: @restaurant } %>
  <% end %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container px-0" data-controller='geolocation'>
  <h1><%= Time.now %></h1>
  <p style="color: green"><%= notice %></p>
  <%= render "form", restaurant: Restaurant.new  %>
  <h1>Restaurants</h1>
  <%= turbo_frame_tag 'restaurants' do %>
    <%= render @restaurants %>
  <% end %>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Rating</th>
      <th scope="col">Created at</th>
      <th scope="col">Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant|  %>
      <tr id="<%= dom_id(restaurant, :ts) %>">
        <th scope="row">1</th>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.created_at %></td>
        <td>
          <%= link_to 'Edit TS', form_turbo_stream_path(restaurant), data: {turbo_stream: true} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to "New restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", root_path %>
</div>

app/views/restaurants/new.turbo_stream.erb
<%= turbo_stream.replace "new_restaurant" do %>
  <%= render partial: 'form', locals: { restaurant: @restaurant } %>
<% end %>

app/views/restaurants/show.html.erb
<%= turbo_frame_tag @restaurant do %>
  <p style="color: green"><%= notice %></p>

      <div id="<%= dom_id @restaurant %>" class='border'>
        <p>
          <strong>Name:</strong>
          <%= @restaurant.name %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= @restaurant.address %>
        </p>

        <p>
          <strong>Rating:</strong>
          <%= @restaurant.rating %>
        </p>

        <p>
          <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant), data: {turbo_frame: @restaurant}%> |
          <%= link_to "Back to restaurants", root_path, data: {turbo_frame:  "restaurants" } %>
          <%= button_to "Destroy this restaurant", @restaurant,data: {turbo_frame:  "restaurants" }, method: :delete  %>
        </p>
        <div data-controller="websocket-restaurant"
        data-restaurant-id-value="<%= @restaurant %>"></div>
      </div>


<% end %>

app/views/restaurants/update.turbo_stream.erb
<%= turbo_stream.update dom_id @restaurant, partial: "restaurant", locals: { restaurant: @restaurant } %>
<%= turbo_stream.replace "my-alert", partial: "shared/flashes" %>

app/views/shared/_flashes.html.erb
<div id="my-alert">
  <% if notice %>
    <div class="notice" role="alert">
      <%= notice %>

      <i class="fa-solid fa-check"></i>
      <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button> %>
    </div>
  <% end %>


  <script>
    setTimeout(function() {
      var myAlert = document.querySelector('#my-alert');
      if (myAlert) {
        var notice = myAlert.querySelector('.notice');
        if (notice) {
          setTimeout(function() {
            notice.classList.add('slide-out-right'); // Agrega la clase slide-out-right después de 5 segundos
            setTimeout(function() {
              myAlert.innerHTML = '';
            }, 1000); // Espera 1 segundo para eliminar el elemento
          }, 5000); // La alerta se cerrará después de 5 segundos (5000 milisegundos)
        }
      }
    }, 1000);
  </script>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>